name: "Update data-media-marketing-resoures"
description: "Updates resource list at collinberke.com/data-media-marketing-resources.html"

on: [workflow_dispatch]

jobs:

  build:
    name: Build environment
    runs-on: ubuntu-latest
    steps:

      # More here: https://github.com/actions/checkout
      - name: Checkout repo code
        uses: actions/checkout@v6

      # More here: https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      # More here: https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies
      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
      
      # More here: https://github.com/quarto-dev/quarto-actions/tree/main/setup
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check Quarto version
        run: |
          quarto --version

      # More here: https://github.com/quarto-dev/quarto-actions/tree/main/render
      - name: Render Quarto report
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: data-media-marketing-resources.qmd

      - name: List files in directory
        run: |
          ls -a

      # Attribute commit to bot account
      - name: Commit and push updated resource list to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data-media-marketing-resources" -m "Changes here: https://www.collinberke.com/data-media-marketing-resources.html"
          git push
